### ISSUE TITLE
Pixmap is a null pixmap

### ISSUE THREAD

**Issue by SummerHuiZhang** [Photogrammetry-Robotics-Bonn/online_place_recognition#1]
I extract Alderley datasets of Sunny_Day and Rainy_Night.
Firstly, I compared two identical sequences, so the expected result should be a diagonal line, which it is. So this is correct. However, the two windows have no photos been retrieved, which said "**Pixmap is a null pixmap".**

**Comment by ovysotska** [comment]
Hi @SummerHuiZhang,

If the visualizer is not showing any pictures and you receive the warning similar to this:
```bash
QPixmap::scaled: Pixmap is a null pixmap
```
It means that the code is unable to find the images. In the default `config.yaml` file the parameter `imgExt` is set to ".png". Do your images have ".png" extension? If not try to change the `imgExt` parameter.
