### ISSUE TITLE
vertical line in matching matrix

### ISSUE THREAD

**Issue by SummerHuiZhang** [Photogrammetry-Robotics-Bonn/online_place_recognition#2]
I set Sunny_Day as reference and RainyNight query. However, I get a vertical line in matching matrix, which means that the car is staying within the query sequence.  But in case of Alderley dataset it is not the case.
Olga gave me two situations that might be happening here:
"
1) Your non-matching cost is too high.  This means that you allow images with "high" matching cost to be considered as a match and the system do not differentiate between good and bad matches. To check this try to gradually reduce the non-matching cost until you see blue nodes appearing on the line and check if the shape of the line is changing. If, however, only small amount of red nodes are left, than you restrict your search  to only peak very good matches.

2) Something is wrong with the way the costs are computed.  The only way this search algorithm can give reasonable results is if the "underlying" cost matrix actually has a pattern ( this you in theory should not compute for online case). To check if this is the case you can construct the full matching matrix and see if you as a user can see a pattern in the matrix. For this you can use apps/create_cost_matrix code.  If not, something is wrong with cost computation or the features + metric is not good enough for dealing with such challenges (but I don't think this is the case for Alderley and OverFeat (10th layer)).
"
I am trying these two and will update later.
Thanks so much to Olga.

**Comment by ovysotska** [comment]
@SummerHuiZhang ,

could you please attach the screenshots to your issue. Thanks!

**Comment by SummerHuiZhang** [comment]
The error looks like below. It's really strange the reference and query index matched 
According to the "checking image and matched image" as below, it should be diagonal.
But t's a  vertical line which means that all query night images matched with the same reference day image. 
""......
[DEBUG][OnlineLocalizer] Checking image 995
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
[OnlineLocalizer] Matched image 995
TIMER::Elapsed time 74 ms.
[DEBUG][OnlineLocalizer] Checking image 996
[OnlineLocalizer] Matched image 996
TIMER::Elapsed time 71 ms.
[DEBUG][OnlineLocalizer] Checking image 997
[OnlineLocalizer] Matched image 997
TIMER::Elapsed time 57 ms.
[DEBUG][OnlineLocalizer] Checking image 998
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
[OnlineLocalizer] Matched image 998
TIMER::Elapsed time 77 ms.
[DEBUG][OnlineLocalizer] Localization finished
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
"

**Comment by ovysotska** [comment]
Hey @SummerHuiZhang,
The output you see means something different. 
```bash
(1) [DEBUG][OnlineLocalizer] Checking image 997
(2) [OnlineLocalizer] Matched image 997
````
(1) algorithm started to process query image 997
(2) algorithm finished processing query image 997

The output doesn't show here what is the found image in the reference dataset. So, you can't say based on this console output if the path is "diagonal".
The final results are stored to the `matched_path.txt`.

To fix the issue with the path being vertical, please try two suggestion from your first post.
