### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by SummerHuiZhang** [Photogrammetry-Robotics-Bonn/online_place_recognition#3]
When I create cost matrix with "./create_cost_matrix config.yaml" in folder online_place_recognition/build/bin/, it said:
"
dyld: Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/zhanghui/anaconda/lib/libopencv_stitching.3.2.dylib
  Reason: image not found
Abort trap: 6
"
Besides, my config.yaml writes as below:
path2ref: reference/OverFeat_features/
path2qu: query/OverFeat_features/
querySize: 999
expansionRate: 0.1
fanOut: 1
nonMatchCost: 2.0
path2refImg: reference/images/
path2quImg: query/images/

**Comment by ovysotska** [comment]
@SummerHuiZhang ,

The error seems strange to me. 
Have you tried to run `./create_cost_matrix` with the provided `config.yaml` in the `apps/create_cost/matrix`? Does this work fine for you?
Also, does the error happens after the message `The matrix was saved to file..`?
If so, it just a matter of saving a cost matrix as an image. One can skip this step and still have the computed matrix stored in '.txt' format.

**Comment by SummerHuiZhang** [comment]
@ovysotska Thanks Olga.
I tried the  "run ./create_cost_matrix with the provided config.yaml in the apps/create_cost_matrix".
Unfortunately, it didn't work for me and the error is the same.
After googling, I guess it's caused by Mac OS that it cannot link the dynamic libraries.

**Comment by ovysotska** [comment]
I see, but are able to store the cost matrix in to the ".txt" file?
If so, you can just visualize it with some other tools like Python or Matlab.
