### ISSUE TITLE
About off-line implementation?

### ISSUE THREAD

**Issue by xlong0513** [Photogrammetry-Robotics-Bonn/online_place_recognition#4]
Hi, Thanks for the code.
We want to implement a off-line place recognition. That is, the reference is first gone through to generate a database, then the query will be gone through to achieve place recognition. In this case, the system is more like a loop detection framework. Can u tell us what should we do?

**Comment by ovysotska** [comment]
Hi @xlong0513,

Unfortunately, it is very hard for me to understand what exactly your problem/request is.
Could you please elaborate more on this?

If you are looking for offline visual place recognition, i.e. when the cost matrix is built first, you might want to look at this repository [Offline sequence based visual place recognition](https://github.com/ovysotska/image_sequence_matcher).

**Comment by xlong0513** [comment]
Sorry for the confusion. We are working on a SLAM (simultaneous localization and mapping) project, where "Loop detection" is an important component. First step in loop detection, the scene images (for your code, they are the reference imges) will be captured and used for extract feature points and descriptors in advance, to generate a database. Database is usually a bag of words, such as [DBoW3](https://github.com/rmsalinas/DBow3), and this is an offline process. Then we capture images online and match with the databse to achieve place recognition and locating the position. So my point is, can your code implement an off-line process to generate a database. 
Oh, i will the repository you offerred to me. Thanks for the reply.

**Comment by ovysotska** [comment]
I am glad that helped :+1:
